export default data = [
  {
    name: "John Smith",
    address: "123 Main St",
    city: "New York",
    country: "USA",
    pincode: "10001",
    satScore: "1450",
    passed: "Yes",
  },
  {
    name: "Alice Johnson",
    address: "456 Elm St",
    city: "Los Angeles",
    country: "USA",
    pincode: "90001",
    satScore: "1600",
    passed: "Yes",
  },
  {
    name: "Bob Brown",
    address: "789 Oak St",
    city: "Chicago",
    country: "USA",
    pincode: "60601",
    satScore: "1300",
    passed: "No",
  },
  {
    name: "Eve Wilson",
    address: "101 Pine St",
    city: "San Francisco",
    country: "USA",
    pincode: "94101",
    satScore: "1550",
    passed: "Yes",
  },
  {
    name: "David Lee",
    address: "222 Cedar St",
    city: "Houston",
    country: "USA",
    pincode: "77001",
    satScore: "1420",
    passed: "Yes",
  },
  {
    name: "Sarah Davis",
    address: "333 Birch St",
    city: "Miami",
    country: "USA",
    pincode: "33101",
    satScore: "1500",
    passed: "Yes",
  },
  {
    name: "Michael Clark",
    address: "444 Maple St",
    city: "Boston",
    country: "USA",
    pincode: "02101",
    satScore: "1380",
    passed: "No",
  },
  {
    name: "Linda Turner",
    address: "555 Redwood St",
    city: "Seattle",
    country: "USA",
    pincode: "98101",
    satScore: "1560",
    passed: "Yes",
  },
  {
    name: "William White",
    address: "666 Walnut St",
    city: "Dallas",
    country: "USA",
    pincode: "75201",
    satScore: "1340",
    passed: "No",
  },
  {
    name: "Emily Harris",
    address: "777 Spruce St",
    city: "Phoenix",
    country: "USA",
    pincode: "85001",
    satScore: "1480",
    passed: "Yes",
  },
];
